import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '/styles/Home.module.css'

export default function Home() {
  return (
    <div className='home'>
        <Head>
        <title>Cafe Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/logo.png" />
        </Head>
     
        <div className={styles.hero}>
            <div className={styles.imagecontainer}>
                <div className={styles.outerrectangle1}> 
                    <Link href="/">
                        <div className={styles.innerrectangle1}> 
                            <h1> Cafe Cafe </h1>
                            <h2> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </h2>
                        </div>
                    </Link>
                </div>
                <div className={styles.image}>
                    <Image
                    src={require("/public/cafehero1alt.jpg")}
                    fill={true}
                    alt="Cafe Display"
                    />
                </div>
            </div>

            <div className={styles.imagecontainer}>
                <div className={styles.outerrectangle2}> 
                    <Link href='./AboutUs'>
                        <div className={styles.innerrectangle2}> 
                            <h1> Menu </h1>
                            <h2> Coffee | Bakery | Lunch </h2>
                        </div>
                    </Link>
                </div>
                <div className={styles.image}>
                    <Image
                    src={require("/public/cafehero2alt.jpg")}
                    fill={true}
                    alt="Cafe Display"
                    />
                </div>
            </div>

            <div className={styles.imagecontainer}>
                <div className={styles.outerrectangle3}> 
                    <Link href='./Hours&Locations'>
                        <div className={styles.innerrectangle3}> 
                            <h1> Hours </h1>
                            <h2> & Locations</h2>
                        </div>
                    </Link>
                </div>
                <div className={styles.image}>
                    <Image
                    src={require("/public/cafehero3alt.jpg")}
                    fill={true}
                    alt="Cafe Display"
                    />
                </div>
            </div>


        </div>
     </div> 
  )
}
